OPS-1499-Pronto-Failing-Issue-in-BioSuisse-Update-Ruby-PR
wtag/pronto-action pull request #17
Opened 2023-12-12 07:14 UTC by mram-wtag

[OPS-1499](https://welltravel.atlassian.net/jira/software/c/projects/OPS/issues/OPS-1499)

2023-12-12 08:58 UTC, yra-wtag commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/wtag/default-configs/Update-Rubocop-Config-to-Ruby-3.2/rubocop-default-config-ruby3.2.yml
please change to master before merging
`Update-Rubocop-Config-to-Ruby-3.2`

2023-12-12 08:58 UTC, yra-wtag requested changes

2023-12-12 08:58 UTC, yra-wtag commented on action.yml
> -  image: 'docker://welltravel/pronto-action:latest'
this need to be changed

2023-12-12 11:08 UTC, ssa-wtag commented on Gemfile.lock
> +  x86_64-darwin-22
please also revert this change

2023-12-12 11:48 UTC, ssa-wtag approved these changes
Please make sure right after merging this, other projects pronto don't fail

2023-12-12 18:27 UTC, luxflux approved these changes
To ensure this doesn't fail projects which are still using older versions, I think we have to tag the previous release with `2.6` or so (incl. an appropriate docker image tag).

Then the old projects can call `uses: wtag/pronto-action@2.6` and keep working.

Additionally, I'd suggest to start using tags intead of just `latest` to avoid this situation in future. All the projects should use `uses: wtag/pronto-action@3.2` when they upgrade to Ruby 3.2.

2025-01-05 12:02 UTC, yra-wtag approved these changes
i approved as sec reviewer

2025-01-05 12:04 UTC, merged